# HTTP config
http:
  port: 8080
  origin: "http://localhost:8080"
  # cookie secret
  secret: "top secret"
# application config.
app:
  name: "Brainf*ck系言語を作るやつ"
  description: "Brainf*ck系言語を簡単に作成・公開できるサービスです。"
  origin: "http://localhost:8080"
  author: "@uhyo_"


# length limit of user inputs.
limit:
  # max length of language name.
  name: 100
  # max length of language description.
  description: 3000
  # max length of op.
  op: 50
# Twitter authentication
twitter:
  consumerKey: "*"
  consumerSecret: "*"

# JWT server setting
jwt:
  secret: "high security"
  # StringOrURI value
  issuer: "uhyo/bf-gen"


# MongoDB config
db:
  # name of database
  db: "bf-gen"
  user: "test"
  password: "test"
  # db host
  host: "localhost"
  port: 27017

