# HTTP config
http:
  port: 8080
  origin: "http://localhost:8080"
  # cookie secret
  secret: "top secret"
# Twitter authentication
twitter:
  consumerKey: "*"
  consumerSecret: "*"


# MongoDB config
db:
  # name of database
  db: "bf-gen"
  user: "test"
  password: "test"

