# HTTP config
http:
  port: 8080
  origin: "http://localhost:8080"
  # cookie secret
  secret: "top secret"

# length limit of user inputs.
limit:
  # max length of language name.
  name: 100
  # max length of language description.
  description: 3000
  # max length of op.
  op: 50
# Twitter authentication
twitter:
  consumerKey: "*"
  consumerSecret: "*"

# JWT server setting
jwt:
  secret: "high security"
  # StringOrURI value
  issuer: "uhyo/bf-gen"


# MongoDB config
db:
  # name of database
  db: "bf-gen"
  user: "test"
  password: "test"
  # db host
  host: "localhost"
  port: 27017

